data = read.table("household_power_consumption.txt", sep=";", header = TRUE, dec = ".", na.strings = "?")
data = transform(data, DateTime = paste(data$Date, data$Time))
data$DateTime = strptime(data$DateTime, format = "%d/%m/%Y %H:%M:%S")
feb = subset(data, DateTime>="2007-02-01" & DateTime<"2007-02-03")
png(filename = "plot3.png")  
plot(feb$DateTime, feb$Sub_metering_1, type="l", ylab = "Energy sub metering", xlab="")
points(feb$DateTime, feb$Sub_metering_2, col="red", type = "l")
points(feb$DateTime, feb$Sub_metering_3, col="blue", type = "l")
legend("topright", pch = "-", col = c("black","red", "blue"), legend = c("Sub_metering_1","Sub_metering_2","Sub_metering_3"))
dev.off()
