data = read.table("household_power_consumption.txt", sep=";", header = TRUE, dec = ".", na.strings = "?")
data = transform(data, DateTime = paste(data$Date, data$Time))
data$DateTime = strptime(data$DateTime, format = "%d/%m/%Y %H:%M:%S")
feb = subset(data, DateTime>="2007-02-01" & DateTime<"2007-02-03")
png(filename = "plot1.png")  
hist(feb$Global_active_power, col="red", xlab="Global Active Power (kilowatts)", main = "Global Active Power")
dev.off()
