data = read.table("household_power_consumption.txt", sep=";", header = TRUE, dec = ".", na.strings = "?")
data = transform(data, DateTime = paste(data$Date, data$Time))
data$DateTime = strptime(data$DateTime, format = "%d/%m/%Y %H:%M:%S")
feb = subset(data, DateTime>="2007-02-01" & DateTime<"2007-02-03")
png(filename = "plot2.png")  
plot(feb$DateTime, feb$Global_active_power, type="l", ylab = "Global active power (kilowatts)", xlab="")
dev.off()
